### ISSUE TITLE
主题背景色问题

### ISSUE THREAD

**Issue by chnliquan** [S1ngS1ng/dotFiles#8]
请问readme里面的背景是黑色的，我下载下来的背景色是浅蓝色的，想要黑色的，怎么搞

**Comment by S1ngS1ng** [comment]
@chnliquan 方便的话，截一下图。谢谢

**Comment by unicape** [comment]
![image](https://user-images.githubusercontent.com/31918458/48602996-01e37580-e9b0-11e8-9dbc-c7286d5f9fc8.png)

**Comment by S1ngS1ng** [comment]
@HandsomeManLee 看一下你这里的设置：
![image](https://user-images.githubusercontent.com/13592559/48604787-c739f880-e92f-11e8-9d8a-671640686882.png)
我试了下，如果选 Material Deep Ocean，就会是你截图的效果。

我这里，是选的这个：
![image](https://user-images.githubusercontent.com/13592559/48604891-1849ec80-e930-11e8-9d1b-49852eecae0e.png)

麻烦你找一下，或者都试试看，肯定有一个是从 repo 里提供的 jar 导入的。
我不太清楚导入之后你那里的选项会是什么，如果都不对，再 import 一下那个 jar 包试试。

如果解决了，麻烦你告诉我一下，或者帮我截个图。谢谢 🙏

**Comment by unicape** [comment]
![image](https://user-images.githubusercontent.com/31918458/48614804-1df41080-e9ca-11e8-90f2-28d37d795168.png)

我把WebStorm的所有设置重置，然后重新导入了jar包

但是为什么单词的颜色和你的不一样？

能把你的设置发给我吗？

还有字体大小改怎么调啊？

麻烦您了！

**Comment by S1ngS1ng** [comment]
@HandsomeManLee 我试了下，你这个截图很像是 Material Oceanic 的配色噢。
![image](https://user-images.githubusercontent.com/13592559/48640989-3d207d00-e98d-11e8-9f5d-0649012db539.png)
所以，你应该只需要在上面说的：Editor => Color Scheme 里调一下就好了。
既然你已经导入了 jar 包，那应该是有选项的（我这里，选项叫 Material Theme - Default Copy），那个选项就是我的配色。

印象中，应该是去年吧，Material Theme UI 插件加入了很多个 Color Scheme，之前只有一个，但可以调整深色/浅色背景。我的配色就是根据之前哪一个调的

如果可以，请打开 Color Scheme，截一下图，我看一下你的列表里都有啥。理论上，你在这个列表里换几个试试，应该是可以找到我的 Color Scheme 哈
