### ISSUE TITLE
导入并没有用。。。。

### ISSUE THREAD

**Issue by gavincoder-china** [S1ngS1ng/dotFiles#9]
导入并没有用。。。。
我是2019.1.1版本

**Comment by S1ngS1ng** [comment]
@xunyegege 麻烦你多提供一些信息，只说没有用是很难猜出来发生了什么的。
首先你导入是什么？WebStorm 的还是 Vim 的，还是 `.ideavimrc`？没有用的又是哪个？
如果是 WebStorm 的，右下角有没有报错信息或者提示信息？
导入的时候，你勾选了什么？方便的话再做一次，截个图
如果导入没有报错，是显示不出来么？你有没有安装 Material Theme UI？
重启之后打开你的设置，看看 Color Scheme 里有没有添加：
![image](https://user-images.githubusercontent.com/13592559/56531974-ce31ec00-6509-11e9-97b7-28af3d452ef2.png)

**Comment by gavincoder-china** [comment]
https://ws3.sinaimg.cn/large/005BYqpgly1g2ca1e09v4j30f5081jri.jpg

**Comment by gavincoder-china** [comment]
https://ws3.sinaimg.cn/large/005BYqpggy1g2ca254xlaj310n0lywf4.jpg

**Comment by gavincoder-china** [comment]
https://ws3.sinaimg.cn/large/005BYqpgly1g2ca2f75k4j30z00nzabq.jpg

**Comment by gavincoder-china** [comment]
你好，之前没有描述清楚问题，这是我的锅。我上面放了三张图，麻烦您帮忙看一下，谢谢了。插件我是都装了，你的配置我也是全选的。我喜欢你字体的设置。比如加粗，高亮，都很好看。

**Comment by S1ngS1ng** [comment]
@xunyegege 先谢谢了🙏多提意见
第一个截图的选项不全，不过你应该选了 color scheme，因为第二张里面的 color scheme 能看到
第三张图，可以看出高亮基本没问题。你说的“没有用”指的应该不是高亮吧？具体是什么？
如果是字体，那个 `jar` 里面可能没有，在这里设置就好：
![image](https://user-images.githubusercontent.com/13592559/56561785-c3547700-655c-11e9-9248-519dfea45fdf.png)
